//! Guards against accidental schema drift.
//!
//! The Android app regenerates `data/schemas/org.tasks.data.db.Database/<V>.json`
//! every time Room's schema changes. If a new migration lands upstream while
//! the desktop client still pins an older version, any DB produced by the
//! new Android build would fail to open with an identity-hash mismatch.
//!
//! This test reads the pinned schema JSON from the repository and asserts
//! that its `identityHash` matches `tasks_core::db::PINNED_IDENTITY_HASH`.
//! When it fails, the operator should:
//!   1. Confirm the new schema is backward-compatible for our read path.
//!   2. Update PINNED_SCHEMA_VERSION and PINNED_IDENTITY_HASH together.
//!   3. Audit `tasks-core::models` for any column additions/renames.

use std::path::PathBuf;

use tasks_core::db::{PINNED_IDENTITY_HASH, PINNED_SCHEMA_VERSION};

#[test]
fn pinned_schema_hash_matches_repository() {
    // CARGO_MANIFEST_DIR is the crate directory; the schema JSON lives two
    // levels up in `data/schemas/...`.
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let schema_path = manifest
        .join("../../..")
        .join("data/schemas/org.tasks.data.db.Database")
        .join(format!("{PINNED_SCHEMA_VERSION}.json"));

    let canonical = schema_path
        .canonicalize()
        .unwrap_or_else(|e| panic!("schema file not found at {}: {e}", schema_path.display()));

    let contents = std::fs::read_to_string(&canonical)
        .unwrap_or_else(|e| panic!("read {}: {e}", canonical.display()));

    let actual = extract_identity_hash(&contents)
        .unwrap_or_else(|| panic!("identityHash field missing from {}", canonical.display()));

    assert_eq!(
        actual, PINNED_IDENTITY_HASH,
        "Room schema {PINNED_SCHEMA_VERSION} identity hash drift. Upstream {actual}, pinned {PINNED_IDENTITY_HASH}. See tasks-core/tests/schema_guard.rs for the update procedure."
    );
}

/// Extract the `"identityHash": "<hex>"` value without pulling in a JSON
/// parser. The schema files are generated by Room and always produce this
/// field as a single-line string at the top of the `database` object.
fn extract_identity_hash(contents: &str) -> Option<String> {
    let marker = "\"identityHash\":";
    let start = contents.find(marker)? + marker.len();
    let after = &contents[start..];
    let quote_open = after.find('"')? + 1;
    let after_quote = &after[quote_open..];
    let quote_close = after_quote.find('"')?;
    Some(after_quote[..quote_close].to_string())
}
