//! Generates `schema_<VERSION>.sql` from the Room schema JSON the
//! Android app checks in. `src/db/mod.rs` includes the output via
//! `include_str!`, so the binary can create an empty DB at the
//! pinned schema version without carrying a separate fixture file.
//!
//! Kept in sync with `PINNED_SCHEMA_VERSION` in `src/db/mod.rs` —
//! if you bump one, bump the other.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const PINNED_SCHEMA_VERSION: u32 = 92;

fn main() {
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let schema_json = crate_dir
        .join("../../..")
        .join("data/schemas/org.tasks.data.db.Database")
        .join(format!("{PINNED_SCHEMA_VERSION}.json"))
        .canonicalize()
        .expect("schema JSON must exist at data/schemas/...");

    println!("cargo:rerun-if-changed={}", schema_json.display());
    println!("cargo:rerun-if-changed=build.rs");

    let sql = generate_sql(&schema_json);
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join(format!("schema_{PINNED_SCHEMA_VERSION}.sql"));
    fs::write(&out_path, sql).unwrap_or_else(|e| {
        panic!("write {}: {e}", out_path.display());
    });
}

fn generate_sql(schema_json: &Path) -> String {
    let raw = fs::read_to_string(schema_json)
        .unwrap_or_else(|e| panic!("read {}: {e}", schema_json.display()));
    let root: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("parse {}: {e}", schema_json.display()));
    let database = &root["database"];
    let entities = database["entities"].as_array().expect("entities array");

    let mut sql = String::new();
    sql.push_str("-- Generated by build.rs from the Room schema JSON.\n");
    sql.push_str("-- Do not edit by hand; rerun cargo build after bumping\n");
    sql.push_str("-- PINNED_SCHEMA_VERSION.\n\n");

    for entity in entities {
        let table_name = entity["tableName"].as_str().expect("tableName");
        let create_sql = entity["createSql"]
            .as_str()
            .expect("entity createSql")
            .replace("${TABLE_NAME}", table_name);
        sql.push_str(&create_sql);
        sql.push_str(";\n");

        if let Some(indices) = entity["indices"].as_array() {
            for idx in indices {
                let idx_sql = idx["createSql"]
                    .as_str()
                    .expect("index createSql")
                    .replace("${TABLE_NAME}", table_name);
                sql.push_str(&idx_sql);
                sql.push_str(";\n");
            }
        }
    }

    // room_master_table — Room itself would create this, but since
    // we're standing the file up from scratch we do it explicitly and
    // seed it with the pinned identity hash so
    // `Database::open_read_only` accepts the file on the next open.
    sql.push_str(
        "\nCREATE TABLE IF NOT EXISTS room_master_table \
         (id INTEGER PRIMARY KEY, identity_hash TEXT);\n",
    );

    sql
}
